### ISSUE TITLE
WebSocket connection error after run  `npm run xxx`

### ISSUE THREAD

**Issue by mobilesite** [KyberNetwork/KyberWallet#354]
It seems that there is an error as following after run `npm run ropsten`:

> WebSocket connection to 'wss://ropsten.kyber.network/ws/' failed: Error during WebSocket handshake: Unexpected response code: 404

The same error occurs after run `npm run dev`. Is there any other configuration should added? Thanks!

**Comment by tranvictor** [comment]
Actually the wallet tries to connect to a node using web socket and it will fallback to rpc if it failed. This is expected since we don't support web socket on our node for ropsten. It will be supported in our mainnet launch.

I will close this issue because it is not potentially a bug. Thanks for referring. Please reopen it if you think it is necessary.
